version: "3.8"
services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=change_this_secret
    volumes:
      - ./data:/app/data
    restart: unless-stopped
